---

fail_fast: false

repos:

  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.11.0
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
      - id: shell-lint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
