FROM centos:centos7

# Install puppet agent.
RUN rpm -Uvh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
RUN yum -y install puppet tar hostname; yum clean all

# Patch facter to use /etc/os-release on coreos.
# https://github.com/puppetlabs/facter/pull/845
ADD https://raw.githubusercontent.com/jumanjiman/facter/coreos/lib/facter/operatingsystem/implementation.rb /usr/share/ruby/vendor_ruby/facter/operatingsystem/
ADD https://raw.githubusercontent.com/jumanjiman/facter/coreos/lib/facter/operatingsystem/osreleaselinux.rb /usr/share/ruby/vendor_ruby/facter/operatingsystem/

ENV container docker
VOLUME ["/sys/fs/cgroup, "/run", "/var/lib/puppet"]

ENTRYPOINT ["/usr/bin/puppet"]
CMD ["help"]
