#!/bin/bash
set -e

. script/functions

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

info "Build images."
smitty docker build $options -t puppet .

info "Show image sizes."
docker images | egrep '^puppet\b' | sort

echo
echo "WARN: you should docker tag the puppet image."
echo
