#!/bin/bash
set -e

. test/functions.bash

options="
--rm
--build-arg PUPPET_VERSION=${PUPPET_VERSION}
--build-arg VCS_REF=${VCS_REF}
--build-arg BUILD_DATE=${BUILD_DATE}
"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

info "Build images."
smitty docker build $options -t puppet .

info "Show image sizes."
docker images | egrep '^puppet\b' | sort

echo
echo "WARN: you should docker tag the puppet image."
echo
